# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-growl}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Hodel", "Dylan Markow"]
  s.date = %q{2009-10-01}
  s.default_executable = %q{growl}
  s.description = %q{ruby-growl allows you to perform Growl notification via UDP from machines
without growl installed (for example, non-OSX machines).

What's Growl?  Growl is a really cool "global notification system for Mac OS
X".  See http://growl.info/

See also the Ruby Growl bindings in Growl's subversion repository:
http://growl.info/documentation/growl-source-install.php

ruby-growl also contains a command-line notification tool named 'growl'.  Where possible, it isoption-compatible with growlnotify.  (Use --priority instead of -p.)
}
  s.email = %q{dylan@dylanmarkow.com}
  s.executables = ["growl"]
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "LICENSE",
     "Rakefile",
     "bin/growl",
     "lib/ruby-growl.rb",
     "test/test_ruby-growl.rb"
  ]
  s.homepage = %q{http://github.com/dmarkow/ruby-growl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Pure-Ruby Growl Notifier}
  s.test_files = [
    "test/test_ruby-growl.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
